#!/usr/bin/env bash
set -euo pipefail

# User-level setup for ai-mem.
# Creates config file and wires the MCP server into Claude Code.
#
# Examples:
#   ./02-user-setup.sh
#   DBHOST=myhost DBPORT=5432 ./02-user-setup.sh
#   FORCE_CONFIG=1 ./02-user-setup.sh

DBHOST="${DBHOST:-localhost}"
DBPORT="${DBPORT:-5450}"
DBNAME="${DBNAME:-ai_mem}"
DBUSER="${DBUSER:-ai_mem}"

FORCE_CONFIG="${FORCE_CONFIG:-0}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/ai-mem"
CONFIG_FILE="${CONFIG_DIR}/config.toml"

mkdir -p "$CONFIG_DIR"

if [[ ! -f "$CONFIG_FILE" || "$FORCE_CONFIG" == "1" ]]; then
  cat > "$CONFIG_FILE" <<EOF
# ~/.config/ai-mem/config.toml — generated by 02-user-setup.sh

[database]
host   = "${DBHOST}"
port   = ${DBPORT}
dbname = "${DBNAME}"
user   = "${DBUSER}"
EOF
  echo "Wrote ${CONFIG_FILE}"
else
  echo "Config exists at ${CONFIG_FILE} (set FORCE_CONFIG=1 to overwrite)"
fi

DSN="postgresql://${DBUSER}@${DBHOST}:${DBPORT}/${DBNAME}"
BINARY="${PROJECT_DIR}/target/release/ai-mem-mcp"
MCP_JSON="${PROJECT_DIR}/.mcp.json"

if [[ ! -f "$BINARY" ]]; then
  echo "==> Building release binary"
  cd "$PROJECT_DIR"
  nix develop --command cargo build --release -p ai-mem-mcp
fi

echo "==> Writing ${MCP_JSON}"
cat > "$MCP_JSON" <<EOF
{
  "mcpServers": {
    "ai-mem": {
      "type": "stdio",
      "command": "${BINARY}",
      "env": {
        "AI_MEM_DSN": "${DSN}"
      }
    }
  }
}
EOF

echo "Done."
echo "Restart Claude Code to pick up the ai-mem MCP server."
