use serde::{Deserialize, Serialize};

// ── Embedding config ───────────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "lowercase")]
pub enum EmbeddingBackend {
    Voyage,
    #[serde(rename = "openai")]
    OpenAi,
    Local,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct EmbeddingsConfig {
    pub backend: EmbeddingBackend,
    /// Used by Voyage and OpenAI backends. Ignored for local.
    #[serde(default)]
    pub model: String,
    /// Required for Voyage and OpenAI. Not needed for local.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub api_key: Option<String>,
    /// Local backend: batch size for embedding calls (0 = no limit).
    #[serde(default)]
    pub batch_size: usize,
    /// Local backend: directory to cache downloaded model files.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cache_dir: Option<String>,
}

// ── SSL mode ───────────────────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
#[serde(rename_all = "kebab-case")]
pub enum SslMode {
    Disable,
    #[default]
    Prefer,
    Require,
    VerifyCa,
    VerifyFull,
}

// ── Database config ────────────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct DatabaseConfig {
    // ── Required ──────────────────────────────────────────────────────────
    pub host: String,
    pub port: u16,
    pub dbname: String,
    pub user: String,

    // ── TLS (optional) ────────────────────────────────────────────────────
    /// SSL negotiation mode. Default: prefer.
    #[serde(default)]
    pub ssl_mode: SslMode,
    /// Path to PEM-encoded CA certificate for verify-ca / verify-full.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ssl_root_cert: Option<String>,
    /// Path to PEM-encoded client certificate (mutual TLS).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ssl_client_cert: Option<String>,
    /// Path to PEM-encoded client private key (mutual TLS).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ssl_client_key: Option<String>,
}

// ── Global config ──────────────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Config {
    pub database: DatabaseConfig,
    /// Optional — required for load_document and query_document.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub embeddings: Option<EmbeddingsConfig>,
}

impl Config {
    pub fn config_path() -> std::path::PathBuf {
        let base = std::env::var("XDG_CONFIG_HOME")
            .map(std::path::PathBuf::from)
            .unwrap_or_else(|_| {
                let home = std::env::var("HOME").unwrap_or_default();
                std::path::PathBuf::from(home).join(".config")
            });
        base.join("mimir").join("config.toml")
    }

    pub fn load() -> anyhow::Result<Self> {
        let path = Self::config_path();
        if !path.exists() {
            anyhow::bail!(
                "no config file found at {}\n\
                 Run `mimir init` to create one.",
                path.display()
            );
        }
        let content = std::fs::read_to_string(&path)?;
        Ok(toml::from_str(&content)?)
    }

    /// Write a template config at the default path and return the path.
    /// Fails if the file already exists.
    pub fn create_template() -> anyhow::Result<std::path::PathBuf> {
        let path = Self::config_path();
        if path.exists() {
            anyhow::bail!("config already exists at {}", path.display());
        }
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(&path, CONFIG_TEMPLATE)?;
        Ok(path)
    }
}

const CONFIG_TEMPLATE: &str = r#"# ~/.config/mimir/config.toml — mimir global configuration
#
# Generated by `mimir init`. Edit and save to activate.

[database]

# ── Required ──────────────────────────────────────────────────────────────────
# PostgreSQL server address and application database.
# mimir never stores a password. Add a ~/.pgpass entry instead:
#   HOST:PORT:DBNAME:USER:password
# The file must be chmod 600 or PostgreSQL will ignore it.

host   = "localhost"   # hostname or IP of the PostgreSQL server
port   = 5432          # PostgreSQL port
dbname = "mimir"       # name of the mimir database (must already exist)
user   = "mimir"       # PostgreSQL role used by mimir at runtime

# ── TLS (optional) ────────────────────────────────────────────────────────────
# Controls SSL/TLS negotiation between mimir and PostgreSQL.
#
# ssl_mode values:
#   disable     — never use TLS, even if the server offers it
#   prefer      — try TLS first, fall back to plain text (default)
#   require     — require TLS, but do not verify the server certificate
#   verify-ca   — require TLS and verify the server certificate is signed
#                 by a trusted CA (ssl_root_cert must be set)
#   verify-full — like verify-ca, and also verify the server hostname
#                 matches the certificate CN/SAN (ssl_root_cert must be set)
#
# ssl_mode      = "prefer"
# ssl_root_cert = "/path/to/ca.crt"      # CA certificate for verify-ca / verify-full
#
# Mutual TLS — present a client certificate to the server:
# ssl_client_cert = "/path/to/client.crt"
# ssl_client_key  = "/path/to/client.key"

# ── Embeddings (required for load_document / query_document) ──────────────────
# Without this section, the document RAG tools are disabled.
#
# Three backends are available:
#
#   local  — BGE-Base-EN-v1.5 (768 dims) via fastembed + ONNX Runtime.
#            No API key required. Model (~120 MB) is downloaded from HuggingFace
#            on first use and cached locally. Fully offline after that.
#
#   voyage — Voyage AI API (1024 dims for voyage-3-lite, etc.)
#            Requires api_key from voyageai.com. Never commit this file.
#
#   openai — OpenAI Embeddings API (1536 dims for text-embedding-3-small, etc.)
#            Requires api_key from platform.openai.com. Never commit this file.
#
# All load_document calls must use the same backend/model — mixing models
# produces incorrect similarity rankings and requires a full re-index to fix.
#
# [embeddings]
# backend = "local"
#
# --- or ---
#
# [embeddings]
# backend = "voyage"
# model   = "voyage-3-lite"
# api_key = "pa-..."
"#;
