use serde::{Deserialize, Serialize};

// ── SSL mode ───────────────────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
#[serde(rename_all = "kebab-case")]
pub enum SslMode {
    Disable,
    Allow,
    #[default]
    Prefer,
    Require,
    VerifyCa,
    VerifyFull,
}

// ── Database config ────────────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct DatabaseConfig {
    // ── Required ──────────────────────────────────────────────────────────
    pub host: String,
    pub port: u16,
    pub dbname: String,
    pub user: String,

    // ── TLS (optional) ────────────────────────────────────────────────────
    /// SSL negotiation mode. Default: prefer.
    #[serde(default)]
    pub ssl_mode: SslMode,
    /// Path to PEM-encoded CA certificate for verify-ca / verify-full.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ssl_root_cert: Option<String>,
    /// Path to PEM-encoded client certificate (mutual TLS).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ssl_client_cert: Option<String>,
    /// Path to PEM-encoded client private key (mutual TLS).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ssl_client_key: Option<String>,

    // ── PgBouncer (optional) ──────────────────────────────────────────────
    /// Set to true when connecting through PgBouncer in transaction pooling
    /// mode. Disables the prepared-statement cache (statement_cache_capacity=0)
    /// which is incompatible with that mode. Default: false.
    #[serde(default)]
    pub pgbouncer: bool,

    // ── Pool (optional) ───────────────────────────────────────────────────
    /// Maximum number of connections in the pool. Default: 10.
    #[serde(default = "default_max_connections")]
    pub max_connections: u32,
}

fn default_max_connections() -> u32 {
    10
}

// ── Global config ──────────────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Config {
    pub database: DatabaseConfig,
}

impl Config {
    pub fn config_path() -> std::path::PathBuf {
        let base = std::env::var("XDG_CONFIG_HOME")
            .map(std::path::PathBuf::from)
            .unwrap_or_else(|_| {
                let home = std::env::var("HOME").unwrap_or_default();
                std::path::PathBuf::from(home).join(".config")
            });
        base.join("mimir").join("config.toml")
    }

    pub fn load() -> anyhow::Result<Self> {
        let path = Self::config_path();
        if !path.exists() {
            anyhow::bail!(
                "no config file found at {}\n\
                 Run `mimir init` to create one.",
                path.display()
            );
        }
        let content = std::fs::read_to_string(&path)?;
        Ok(toml::from_str(&content)?)
    }

    /// Write a template config at the default path and return the path.
    /// Fails if the file already exists.
    pub fn create_template() -> anyhow::Result<std::path::PathBuf> {
        let path = Self::config_path();
        if path.exists() {
            anyhow::bail!("config already exists at {}", path.display());
        }
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(&path, CONFIG_TEMPLATE)?;
        Ok(path)
    }
}

const CONFIG_TEMPLATE: &str = r#"# ~/.config/mimir/config.toml — mimir global configuration
#
# Generated by `mimir init`. Edit and save to activate.

[database]

# ── Required ──────────────────────────────────────────────────────────────────
# PostgreSQL server address and application database.
# mimir never stores a password. Add a ~/.pgpass entry instead:
#   HOST:PORT:DBNAME:USER:password
# The file must be chmod 600 or PostgreSQL will ignore it.

host   = "localhost"   # hostname or IP of the PostgreSQL server
port   = 5432          # PostgreSQL port
dbname = "mimir"       # name of the mimir database (must already exist)
user   = "mimir"       # PostgreSQL role used by mimir at runtime

# ── TLS (optional) ────────────────────────────────────────────────────────────
# Controls SSL/TLS negotiation between mimir and PostgreSQL.
#
# ssl_mode values:
#   disable     — never use TLS, even if the server offers it
#   allow       — try plain text first, fall back to TLS if required
#   prefer      — try TLS first, fall back to plain text (default)
#   require     — require TLS, but do not verify the server certificate
#   verify-ca   — require TLS and verify the server certificate is signed
#                 by a trusted CA (ssl_root_cert must be set)
#   verify-full — like verify-ca, and also verify the server hostname
#                 matches the certificate CN/SAN (ssl_root_cert must be set)
#
# ssl_mode      = "prefer"
# ssl_root_cert = "/path/to/ca.crt"      # CA certificate for verify-ca / verify-full
#
# Mutual TLS — present a client certificate to the server:
# ssl_client_cert = "/path/to/client.crt"
# ssl_client_key  = "/path/to/client.key"

# ── PgBouncer (optional) ──────────────────────────────────────────────────────
# Set to true when mimir connects through PgBouncer in transaction pooling mode.
# Transaction pooling mode does not support PostgreSQL prepared statements.
# Setting this to true disables mimir's prepared-statement cache so that all
# queries are sent as simple protocol text, which PgBouncer can safely proxy.
# Leave false (the default) for direct PostgreSQL connections or PgBouncer in
# session pooling mode.
#
# pgbouncer = false

# ── Connection pool (optional) ────────────────────────────────────────────────
# Maximum number of simultaneous PostgreSQL connections mimir will open.
# Increase if you see connection-wait latency under heavy concurrent load;
# decrease if the PostgreSQL server has a low max_connections limit.
#
# max_connections = 10
"#;